// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using REPETITEURLINK;

#nullable disable

namespace REPETITEURLINK.Migrations
{
    [DbContext(typeof(RepetitionLinkDataContext))]
    [Migration("20260118142742_evolue3")]
    partial class evolue3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.DirectoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<bool>("IsNative")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("DirectoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff12163-8fdc-4657-80d0-c510a27b54df"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Cameroun",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Country",
                            Value = "CM"
                        },
                        new
                        {
                            Id = new Guid("5330d345-8ecf-4a94-8de2-742d448c52fb"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "FCFA",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Currency",
                            Symbol = "XAF",
                            Value = "XAF"
                        },
                        new
                        {
                            Id = new Guid("753e4bf2-f965-4f7c-b2ff-64b34cbe7fbb"),
                            CountryId = new Guid("8ff12163-8fdc-4657-80d0-c510a27b54df"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Yaoundé",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "City",
                            Value = "YAOUNDE"
                        },
                        new
                        {
                            Id = new Guid("d3873ec8-cb6b-482e-9ba3-90facc2b3fb1"),
                            CountryId = new Guid("8ff12163-8fdc-4657-80d0-c510a27b54df"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Douala",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "City",
                            Value = "DOUALA"
                        },
                        new
                        {
                            Id = new Guid("ca10411d-8f52-4ad8-aeba-1e1bd634fa61"),
                            CountryId = new Guid("8ff12163-8fdc-4657-80d0-c510a27b54df"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bafoussam",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "City",
                            Value = "BAFOUSSAM"
                        },
                        new
                        {
                            Id = new Guid("f5b9bf9f-c280-4301-99b7-4ac73cc9b167"),
                            CountryId = new Guid("8ff12163-8fdc-4657-80d0-c510a27b54df"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bamenda",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "City",
                            Value = "BAMENDA"
                        },
                        new
                        {
                            Id = new Guid("004a71f4-0612-4926-b36c-1f845d387e61"),
                            CountryId = new Guid("8ff12163-8fdc-4657-80d0-c510a27b54df"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Garoua",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "City",
                            Value = "GAROUA"
                        },
                        new
                        {
                            Id = new Guid("a8ac01dd-40ea-4b8a-b6a0-bb66f4c88275"),
                            CityId = new Guid("753e4bf2-f965-4f7c-b2ff-64b34cbe7fbb"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bastos",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "BASTOS"
                        },
                        new
                        {
                            Id = new Guid("ca21bd6d-3506-4951-9c5d-192aec6356f9"),
                            CityId = new Guid("753e4bf2-f965-4f7c-b2ff-64b34cbe7fbb"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Biyem-Assi",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "BIYEM_ASSI"
                        },
                        new
                        {
                            Id = new Guid("75564c79-4adf-4c72-a09e-670d4ce331fd"),
                            CityId = new Guid("753e4bf2-f965-4f7c-b2ff-64b34cbe7fbb"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mokolo",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "MOKOLO"
                        },
                        new
                        {
                            Id = new Guid("73ce5015-cba6-4ac1-b592-ee6cf853f2ea"),
                            CityId = new Guid("753e4bf2-f965-4f7c-b2ff-64b34cbe7fbb"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Nkolbisson",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "NKOLOBISSON"
                        },
                        new
                        {
                            Id = new Guid("96caf3d2-bfc6-4b96-a76f-83dfb1bca49f"),
                            CityId = new Guid("d3873ec8-cb6b-482e-9ba3-90facc2b3fb1"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Akwa",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "AKWA"
                        },
                        new
                        {
                            Id = new Guid("89574e90-4a05-45f9-9a40-dd7b201c35f4"),
                            CityId = new Guid("d3873ec8-cb6b-482e-9ba3-90facc2b3fb1"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bonapriso",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "BONAPRISO"
                        },
                        new
                        {
                            Id = new Guid("5ae2b031-492d-4363-b10d-aa50acafaa52"),
                            CityId = new Guid("d3873ec8-cb6b-482e-9ba3-90facc2b3fb1"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bonabéri",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "BONABERI"
                        },
                        new
                        {
                            Id = new Guid("d624e25c-40cf-408a-9f2c-7125a1d01079"),
                            CityId = new Guid("d3873ec8-cb6b-482e-9ba3-90facc2b3fb1"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "New Bell",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "NEW_BELL"
                        },
                        new
                        {
                            Id = new Guid("595f9ff8-953b-420f-b51c-efc964ed4843"),
                            CityId = new Guid("ca10411d-8f52-4ad8-aeba-1e1bd634fa61"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Banengo",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "BANENGO"
                        },
                        new
                        {
                            Id = new Guid("92585578-3805-49c7-9263-3bbd5d8a606b"),
                            CityId = new Guid("ca10411d-8f52-4ad8-aeba-1e1bd634fa61"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Djeleng",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "DJELENG"
                        },
                        new
                        {
                            Id = new Guid("4364d167-79f2-4a03-89d2-c09ea5c8ffbe"),
                            CityId = new Guid("f5b9bf9f-c280-4301-99b7-4ac73cc9b167"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mankon",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "MANKON"
                        },
                        new
                        {
                            Id = new Guid("8f62af8c-74c2-417c-bd73-17ead0a34c44"),
                            CityId = new Guid("f5b9bf9f-c280-4301-99b7-4ac73cc9b167"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Nkwen",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "NKWEN"
                        },
                        new
                        {
                            Id = new Guid("15470d97-c076-4ab3-82ae-c4a6d06c2188"),
                            CityId = new Guid("004a71f4-0612-4926-b36c-1f845d387e61"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Padama",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "PADAMA"
                        },
                        new
                        {
                            Id = new Guid("b1ae7aa2-c80c-4aee-ba64-434c2d1932a9"),
                            CityId = new Guid("004a71f4-0612-4926-b36c-1f845d387e61"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bénoué",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "Neighborhood",
                            Value = "BENUE"
                        },
                        new
                        {
                            Id = new Guid("c9f478d1-903a-4ee6-84ed-92608e293c47"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sixième",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "6E"
                        },
                        new
                        {
                            Id = new Guid("4ccc720d-cb3f-4915-a268-43e6e699d3b2"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Cinquième",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "5E"
                        },
                        new
                        {
                            Id = new Guid("2b4d8461-240b-4e1b-84f4-f7148b4da0d3"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Quatrième",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "4E"
                        },
                        new
                        {
                            Id = new Guid("28a67a7d-03ef-40df-b91b-3ce45a6bcfb1"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Troisième",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "3E"
                        },
                        new
                        {
                            Id = new Guid("ac3fdc3d-beb7-4806-9413-384a32c21e1a"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Seconde",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "SECONDE"
                        },
                        new
                        {
                            Id = new Guid("18972a21-ee93-45fe-b337-8e1ec2a7657b"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Première",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "PREMIERE"
                        },
                        new
                        {
                            Id = new Guid("c0a60a47-3d81-4a8a-8582-267410320fb7"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Terminale",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "TERMINALE"
                        },
                        new
                        {
                            Id = new Guid("c2e86c42-1eb7-4cb3-9247-632ccc7960bb"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Licence 1",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "L1"
                        },
                        new
                        {
                            Id = new Guid("ac2e4a38-4d9d-460d-ab37-f4b4ea14df5e"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Licence 2",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "L2"
                        },
                        new
                        {
                            Id = new Guid("b8a19c5a-6a48-4143-b391-313fb95d89dd"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Licence 3",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "L3"
                        },
                        new
                        {
                            Id = new Guid("262aef51-3b3e-4f52-8bb2-f912b288b7c0"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Master 1",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "M1"
                        },
                        new
                        {
                            Id = new Guid("399f1a29-ab8f-409a-abd8-b936c3f66f29"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Master 2",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "M2"
                        },
                        new
                        {
                            Id = new Guid("6896174a-96f1-456e-83a5-de5861d9123b"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Class 1",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "CLASS_1"
                        },
                        new
                        {
                            Id = new Guid("877636e7-73a4-498a-b12a-96d78424d123"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Class 2",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "CLASS_2"
                        },
                        new
                        {
                            Id = new Guid("6b4435c7-ba35-4ed4-9281-4e10092b3cfc"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Class 3",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "CLASS_3"
                        },
                        new
                        {
                            Id = new Guid("350641cf-22c4-45b6-a222-8ce2b93a1770"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Class 4",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "CLASS_4"
                        },
                        new
                        {
                            Id = new Guid("278b6e0a-f892-43e5-803e-5322c78620f3"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Class 5",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "CLASS_5"
                        },
                        new
                        {
                            Id = new Guid("e9e7e694-63df-4e16-bb30-fc3f4437a30c"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Class 6",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "CLASS_6"
                        },
                        new
                        {
                            Id = new Guid("025e1c40-4593-47de-bc4e-b389c91c45fb"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Form 1",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "FORM_1"
                        },
                        new
                        {
                            Id = new Guid("64478a7c-f553-4409-9b20-aa5eda6010bd"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Form 2",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "FORM_2"
                        },
                        new
                        {
                            Id = new Guid("8092a7e1-6773-4ead-9204-15c653bbb55a"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Form 3",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "FORM_3"
                        },
                        new
                        {
                            Id = new Guid("22398de3-c316-41ff-a09d-41f15a856ba4"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Form 4",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "FORM_4"
                        },
                        new
                        {
                            Id = new Guid("9d682bb1-dcb5-4ac6-be8f-5403e3880971"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Form 5",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "FORM_5"
                        },
                        new
                        {
                            Id = new Guid("b77ca2cc-fb1f-4795-a722-c2fb9ccef8aa"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Lower Sixth",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "LOWER_SIXTH"
                        },
                        new
                        {
                            Id = new Guid("1d54025c-b1d8-4baf-8aac-0d37a14d4e52"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Upper Sixth",
                            IsDeleted = false,
                            IsNative = true,
                            Kind = "SchoolClassLevel",
                            Value = "UPPER_SIXTH"
                        });
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.DocumentCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<string>("DocumentSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.Property<Guid>("VerificationCertificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationCertificationId");

                    b.ToTable("DocumentCertifications");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Encadreur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsCertified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Encadreurs");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.LevelSubjectEncadreur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<Guid>("EncadreurId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<Guid>("SchoolLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EncadreurId");

                    b.HasIndex("SchoolLevelId");

                    b.HasIndex("SubjectId");

                    b.ToTable("LevelSubjectEncadreurs");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.MessagePayload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<decimal>("MediaSize")
                        .HasColumnType("numeric");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.Property<string>("_ExtraJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MessagePayloads");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.MessageRequestCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MessagePayloadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestCourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MessagePayloadId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("RequestCourseId");

                    b.HasIndex("SenderId");

                    b.ToTable("MessageRequestCourses");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.MessageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MessagePayloadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionRepetitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MessagePayloadId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SessionRepetitionId");

                    b.ToTable("MessageSessions");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Repetition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<int[]>("DayOfWeeks")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<Guid>("EncadreurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<Guid>("RequestCourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EncadreurId");

                    b.HasIndex("RequestCourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Repetitions");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.RequestCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<Guid>("EncadreurId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EncadreurId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestCourses");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.SessionRepetition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<Guid>("RepetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubjectRepetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RepetitionId");

                    b.HasIndex("SubjectRepetitionId");

                    b.ToTable("SessionRepetitions");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<Guid>("SchoolLevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<decimal>("AverageHourlyRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            AverageHourlyRate = 2500m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Anglais",
                            IsDeleted = false,
                            Name = "Anglais"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            AverageHourlyRate = 2500m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Français",
                            IsDeleted = false,
                            Name = "Francais"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            AverageHourlyRate = 3000m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Informatique",
                            IsDeleted = false,
                            Name = "Informatique"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            AverageHourlyRate = 2800m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mathématiques",
                            IsDeleted = false,
                            Name = "Mathematiques"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            AverageHourlyRate = 2700m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Physique, Chimie et Technologie",
                            IsDeleted = false,
                            Name = "PCT"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                            AverageHourlyRate = 2600m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "SCIENCE DE LA VIE ET DE LA TERRE",
                            IsDeleted = false,
                            Name = "SVT"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d"),
                            AverageHourlyRate = 2750m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Physique",
                            IsDeleted = false,
                            Name = "Physique"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"),
                            AverageHourlyRate = 2750m,
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Chimie",
                            IsDeleted = false,
                            Name = "Chimie"
                        });
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.SubjectRepetition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<Guid>("LevelSubjectEncadreurId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LevelSubjectEncadreurId");

                    b.HasIndex("RepetitionId");

                    b.ToTable("SubjectRepetitions");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ParentSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentSubjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c211feb2-e860-473e-8165-8bc7994a5b3c"),
                            CityId = new Guid("d3873ec8-cb6b-482e-9ba3-90facc2b3fb1"),
                            CreatedAt = new DateTime(2025, 1, 16, 23, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nganjienzatsi@gmail.com",
                            FirstName = "NGANJIE NZATSI",
                            IsDeleted = false,
                            IsEmailVerified = false,
                            LastName = "THEDE REINEL",
                            ParentSubjectType = "None",
                            Password = "$2a$11$/YVnx3p1BFzKTy4OzUXLROtnKLMsQGTvx9a5uo/qmE/kYVkZDOZAW",
                            PhoneNumber = "679015958",
                            Role = "SuperAdmin",
                            Sexe = "Male"
                        });
                });

            modelBuilder.Entity("VerificationCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasJsonPropertyName("id");

                    b.Property<string>("CertificationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("VerificationCertifications");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.DirectoryItem", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.DirectoryItem", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("REPETITEURLINK.Entities.Data.DirectoryItem", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.DocumentCertification", b =>
                {
                    b.HasOne("VerificationCertification", "VerificationCertification")
                        .WithMany()
                        .HasForeignKey("VerificationCertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerificationCertification");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Encadreur", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.LevelSubjectEncadreur", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.Encadreur", "Encadreur")
                        .WithMany()
                        .HasForeignKey("EncadreurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.DirectoryItem", "SchoolLevel")
                        .WithMany()
                        .HasForeignKey("SchoolLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encadreur");

                    b.Navigation("SchoolLevel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.MessageRequestCourse", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.MessagePayload", "MessagePayload")
                        .WithMany()
                        .HasForeignKey("MessagePayloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.RequestCourse", "RequestCourse")
                        .WithMany()
                        .HasForeignKey("RequestCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessagePayload");

                    b.Navigation("Receiver");

                    b.Navigation("RequestCourse");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.MessageSession", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.MessagePayload", "MessagePayload")
                        .WithMany()
                        .HasForeignKey("MessagePayloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.SessionRepetition", "SessionRepetition")
                        .WithMany()
                        .HasForeignKey("SessionRepetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessagePayload");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("SessionRepetition");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Parent", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Repetition", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.Encadreur", "Encadreur")
                        .WithMany()
                        .HasForeignKey("EncadreurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.RequestCourse", "RequestCourse")
                        .WithMany()
                        .HasForeignKey("RequestCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encadreur");

                    b.Navigation("RequestCourse");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.RequestCourse", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.Encadreur", "Encadreur")
                        .WithMany()
                        .HasForeignKey("EncadreurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encadreur");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.SessionRepetition", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.Repetition", "Repetition")
                        .WithMany()
                        .HasForeignKey("RepetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.SubjectRepetition", "SubjectRepetition")
                        .WithMany()
                        .HasForeignKey("SubjectRepetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repetition");

                    b.Navigation("SubjectRepetition");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.Student", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.DirectoryItem", "SchoolLevel")
                        .WithMany()
                        .HasForeignKey("SchoolLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.SubjectRepetition", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.LevelSubjectEncadreur", "LevelSubjectEncadreur")
                        .WithMany()
                        .HasForeignKey("LevelSubjectEncadreurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPETITEURLINK.Entities.Data.Repetition", "Repetition")
                        .WithMany()
                        .HasForeignKey("RepetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelSubjectEncadreur");

                    b.Navigation("Repetition");
                });

            modelBuilder.Entity("REPETITEURLINK.Entities.Data.User", b =>
                {
                    b.HasOne("REPETITEURLINK.Entities.Data.DirectoryItem", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
